
name: docs-action

on:
  push:
    branches: [ develop, develop/*, develop* ]

jobs:
 docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: doxygen run
      run: "sudo apt-get update -yqq -o::Dpkg::Use-Pty=0 && sudo apt-get install -yqq -o::Dpkg::Use-Pty=0 doxygen && cd docs && doxygen"

    - uses: Algo-ryth-mix/sphinx-action@master
      with:
        docs-folder: "docs/"


